# V1

#
RESOURCE_V1_TSE_FONTE = 'fontes'
RESOURCE_V1_TSE_PAIS = 'paises'
RESOURCE_V1_TSE_UNIDADE_FEDERATIVA = 'unidadesFederativas'
RESOURCE_V1_TSE_MUNICIPIO = 'municipios'
RESOURCE_V1_TSE_PESSOA_FISICA = 'pessoasFisicas'
RESOURCE_V1_TSE_PARTIDO = 'partidos'
RESOURCE_V1_TSE_COLIGACAO_PARTIDARIA = 'coligacoesPartidarias'
RESOURCE_V1_TSE_CARGO = 'cargos'
RESOURCE_V1_TSE_PLEITO_GERAL = 'pleitosGerais'
RESOURCE_V1_TSE_PLEITO_REGIONAL = 'pleitosRegionais'
RESOURCE_V1_TSE_CANDIDATURA = 'candidaturas'
RESOURCE_V1_TSE_CANDIDATURA_BEM = 'bens'

#
RESOURCE_URL_V1_TSE_FONTE = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_FONTE}
RESOURCE_URL_V1_TSE_PAIS = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_PAIS}
RESOURCE_URL_V1_TSE_UNIDADE_FEDERATIVA = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_UNIDADE_FEDERATIVA}
RESOURCE_URL_V1_TSE_MUNICIPIO = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_MUNICIPIO}
RESOURCE_URL_V1_TSE_PESSOA_FISICA = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_PESSOA_FISICA}
RESOURCE_URL_V1_TSE_PARTIDO = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_PARTIDO}
RESOURCE_URL_V1_TSE_COLIGACAO_PARTIDARIA = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_COLIGACAO_PARTIDARIA}
RESOURCE_URL_V1_TSE_CARGO = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_CARGO}
RESOURCE_URL_V1_TSE_PLEITO_GERAL = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_PLEITO_GERAL}
RESOURCE_URL_V1_TSE_PLEITO_REGIONAL = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_PLEITO_REGIONAL}
RESOURCE_URL_V1_TSE_CANDIDATURA = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_CANDIDATURA}
RESOURCE_URL_V1_TSE_CANDIDATURA_BEM = '/v1/tse/%(resource)s' % {'resource': RESOURCE_V1_TSE_CANDIDATURA_BEM}